path = ["/Users/elpsycongroo/.pyenv/shims", "/usr/local/sbin", "/usr/local/bin", "/Users/elpsycongroo/.cargo/bin", "/Users/elpsycongroo/.nvm/versions/node/v9.11.2/bin", "/usr/bin", "/bin", "/usr/sbin", "/sbin"]
prompt = "echo $(starship prompt)"
startup = ["alias openstack [OS_IDENTITY_API_VERSION OS_USER_DOMAIN_NAME OS_PROJECT_DOMAIN_NAME OS_TENANT_ID OS_TENANT_NAME OS_PROJECT_DOMAIN_NAME OS_USERNAME OS_PASSWORD OS_REGION_NAME] { docker run -it --rm -v ~/.ssh:$HOME/.ssh:ro -e $OS_AUTH_URL -e $OS_IDENTITY_API_VERSION -e $OS_USER_DOMAIN_NAME -e $OS_PROJECT_DOMAIN_NAME -e $OS_TENANT_ID -e $OS_TENANT_NAME -e $OS_PROJECT_DOMAIN_NAME -e $OS_USERNAME -e $OS_PASSWORD -e $OS_REGION_NAME ullbergm/openstack-client:latest openstack }"]

[env]
COLORFGBG = "7;0"
COLORTERM = "truecolor"
HOME = "/Users/elpsycongroo"
ITERM_PROFILE = "Default"
ITERM_SESSION_ID = "w2t0p0:DA74A11A-0A52-49A9-BF56-B67E2C147DBD"
LANG = "en_GB.UTF-8"
LC_TERMINAL = "iTerm2"
LC_TERMINAL_VERSION = "3.3.9"
LESS = "-R"
LOGNAME = "elpsycongroo"
LSCOLORS = "Gxfxcxdxbxegedabagacad"
NVM_BIN = "/Users/elpsycongroo/.nvm/versions/node/v9.11.2/bin"
NVM_CD_FLAGS = "-q"
NVM_DIR = "/Users/elpsycongroo/.nvm"
NVM_INC = "/Users/elpsycongroo/.nvm/versions/node/v9.11.2/include/node"
OLDPWD = "/Users/elpsycongroo"
P9K_SSH = "0"
P9K_TTY = "new"
PAGER = "less"
PWD = "/Users/elpsycongroo"
PYENV_SHELL = "zsh"
SHELL = "/bin/zsh"
SHLVL = "1"
SSH_AUTH_SOCK = "/private/tmp/com.apple.launchd.g8nr9b0AmH/Listeners"
TERM = "xterm-256color"
TERM_PROGRAM = "iTerm.app"
TERM_PROGRAM_VERSION = "3.3.9"
TERM_SESSION_ID = "w2t0p0:DA74A11A-0A52-49A9-BF56-B67E2C147DBD"
TMPDIR = "/var/folders/m9/n0dl0ym116j_69khvd7z2vx00000gn/T/"
USER = "elpsycongroo"
XPC_FLAGS = "0x0"
XPC_SERVICE_NAME = "0"
_ = "/usr/local/bin/nu"
__CF_USER_TEXT_ENCODING = "0x1F5:0:0"
